spring.application.name=postcompare
server.error.include-message=never
server.error.include-stacktrace=never
management.endpoints.web.exposure.include=health
server.shutdown=graceful
spring.jackson.deserialization.accept-float-as-int=false
